version: "3.4"

services:
  djangotailwind:
    image: djangotailwind
    container_name: django-tailwind-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
