# Generated by Django 4.1.5 on 2023-07-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolean_field', models.BooleanField(default=False)),
                ('integer_field', models.IntegerField(default=0)),
                ('char_field', models.CharField(max_length=100)),
                ('decimal_field', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('date_field', models.DateField(auto_now_add=True)),
                ('choice_field', models.IntegerField(choices=[(0, 'Choice Zero'), (1, 'Choice One'), (2, 'Choice Two')])),
            ],
            options={
                'verbose_name': 'MyModel',
                'verbose_name_plural': 'MyModels',
                'ordering': ['char_field'],
            },
        ),
    ]
